In [1]:
!pip install numpy

twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
jupyterlab-server 1.0.0 has requirement jsonschema>=3.0.1, but you'll have jsonschema 2.6.0 which is incompatible.
You are using pip version 10.0.1, however version 19.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [3]:
import numpy as np

In [22]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [13]:
num=[1,2,3,4]
print(type(num))
print(type(arr))
print(arr)
print(num)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4]
[1, 2, 3, 4]


In [15]:
b = np.array([[1, 2, 3], [4, 5, 6], [6, 7, 8]])
print(b)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [17]:
b.shape

(3, 3)

In [20]:
b.dtype

dtype('int32')

In [60]:
np.zeros((4,5), dtype=np.int32)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [61]:
np.diag([3,3,3])


array([[3, 0, 0],
       [0, 3, 0],
       [0, 0, 3]])

In [18]:
arr.shape

(4,)

In [21]:
lst_1 = [i for i in range(10)]
print(lst_1)
print(type(lst_1))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [26]:
a=np.arange(11)
print(type(a))
print(a)
a.shape

<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10]


(11,)

In [28]:
#PERFORMANCE measurement
c=range(10000)
%timeit[i**3 for i in c]

20.4 ms ± 2.27 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [29]:
c_numpy=np.arange(10000)
%timeit[i**3 for i in c_numpy]

10.3 ms ± 138 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [31]:
#CREATING NUMPY ARRAY
a=np.arange(10,20,2)
print(a)

[10 12 14 16 18]


In [64]:
np.zeros((5,3) , dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [65]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [66]:
np.full((3,3),1)#,dtype=np.float32)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [70]:
np.random.seed(53)
print(np.random.random())

0.8466624072101339


In [117]:

x = np.random.random((4, 4))
print(x)

[[0.35981006 0.94892733 0.7200288  0.30113836]
 [0.26713229 0.59350526 0.26179553 0.57537396]
 [0.53769606 0.37156294 0.26315835 0.90782452]
 [0.34448872 0.1968116  0.99028791 0.54478819]]


In [118]:
print(x)

[[0.35981006 0.94892733 0.7200288  0.30113836]
 [0.26713229 0.59350526 0.26179553 0.57537396]
 [0.53769606 0.37156294 0.26315835 0.90782452]
 [0.34448872 0.1968116  0.99028791 0.54478819]]


In [119]:
x=np.arange(24)

In [120]:
x.shape

(24,)

In [121]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [122]:
x.reshape(3,2)

ValueError: cannot reshape array of size 24 into shape (3,2)

In [55]:
x.shape

(24,)

In [81]:
#Rounding
x=np.random.random((4,4))
print(x)

[[0.47766207 0.71093358 0.21140509 0.70134567]
 [0.89776649 0.67944913 0.19305661 0.54069283]
 [0.87479584 0.57738215 0.3292028  0.55757905]
 [0.17687896 0.6708299  0.86826272 0.48032512]]


In [82]:
rounded=np.round(x,2)
rounded

array([[0.48, 0.71, 0.21, 0.7 ],
       [0.9 , 0.68, 0.19, 0.54],
       [0.87, 0.58, 0.33, 0.56],
       [0.18, 0.67, 0.87, 0.48]])

In [83]:
new=rounded*100
new

array([[48., 71., 21., 70.],
       [90., 68., 19., 54.],
       [87., 58., 33., 56.],
       [18., 67., 87., 48.]])

In [85]:
intt=new.astype(np.int32)

In [86]:
intt

array([[48, 71, 21, 70],
       [90, 68, 19, 54],
       [87, 57, 33, 56],
       [18, 67, 87, 48]])

In [87]:
a=np.array([10,20,30,40,50,60])
print(a)

[10 20 30 40 50 60]


In [88]:
#slicing
a[2::2]

array([30, 50])

In [89]:
a[0:3]

array([10, 20, 30])

In [104]:
sub=np.arange(10)
print(type(sub))

<class 'numpy.ndarray'>


In [105]:
sub

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
sub_a=sub

In [112]:
sub_a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
sub_a[5]=11

In [114]:
sub

array([ 0,  1,  2,  3,  4, 11,  6,  7,  8,  9])

In [127]:
np.shares_memory(sub_a,sub)

True

In [128]:
x=np.arange(20)

In [129]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [130]:
y=x.copy()

In [131]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [132]:
np.shares_memory(x,y)

False

In [152]:
a=np.array([1,1,0],dtype=bool)
b=np.array([0,0,0],dtype=bool)
np.all(a==a)

True

In [160]:
a=np.random.random((3,3))
a

array([[0.20920212, 0.18532822, 0.10837689],
       [0.21969749, 0.97862378, 0.81168315],
       [0.17194101, 0.81622475, 0.27407375]])

In [161]:
np.max(a)

0.9786237847073697

In [163]:
np.argmax(a,axis=0)

array([1, 1, 1], dtype=int64)

In [164]:
np.argmax(a,axis=1)

array([0, 1, 1], dtype=int64)

In [162]:
np.argmax(a)

4

In [165]:
np.argsort(a)

array([[2, 1, 0],
       [0, 2, 1],
       [0, 2, 1]], dtype=int64)